### PR TITLE
Remove http as a default listening server. 

### PR DESCRIPTION
**Pull request by 1000TurquoisePogs**
Just use https. Fix for specifying https via -s on command line

Signed-off-by: 1000TurquoisePogs <sgrady@rocketsoftware.com>

### CODE REVIEW

**Comment by 1000TurquoisePogs** [comment]
Please note that this likely breaks the zowe installer which sets up port configuration! That should have a related change.

**Comment by jackjia-ibm** [comment]
@1000TurquoisePogs related issues are created to track the progress:

- https://github.com/zowe/zowe-install-packaging/issues/129
- https://github.com/zowe/zowe-install-test/issues/36

**Comment by 1000TurquoisePogs** [comment]
This will also break zlux-proxy-server at the moment since it has some of its proxying assuming http port is listening. I have a fix that I will be pushing out as a PR hopefully this week.

**Comment by 1000TurquoisePogs** [comment]
Fix so that it wont break zlux-proxy-server: https://github.com/zowe/zlux-proxy-server/pull/22

**Comment by Joe-Winchester** [comment]
@1000TurquoisePogs - looking at the install changes needed for 1.0.  This pull request needs a review before being delivered.  Do you think this might be done soon so that https://github.com/zowe/zowe-install-packaging/issues/129 can be worked on to remove the http:// port options during the install ?

**Pull request merged**
